export interface Tool {
  slug: string;
  title: string;
  description: string;
  category: string;
  categorySlug: string;
  icon: string;
  color: string;
  keywords: string[];
  isNew?: boolean;
  isFeatured?: boolean;
}

export interface Category {
  slug: string;
  title: string;
  description: string;
  icon: string;
  color: string;
  tools: Tool[];
}

export const tools: Tool[] = [
  {
    slug: "inflation-calculator",
    title: "Inflation Calculator",
    description: "Calculate the real value of money over time using historical CPI data. Adjust for salary, future values, and purchasing power.",
    category: "Finance",
    categorySlug: "finance",
    icon: "TrendingUp",
    color: "blue",
    keywords: ["inflation calculator", "cpi calculator", "purchasing power", "salary inflation"],
    isFeatured: true,
  },
  {
    slug: "fertilizer-calculator",
    title: "Fertilizer Calculator",
    description: "25+ crops, 20+ fertilizers, Indian area units, split application schedule, cost optimizer. The most complete free fertilizer calculator.",
    category: "Agriculture",
    categorySlug: "agriculture",
    icon: "Sprout",
    color: "green",
    keywords: ["fertilizer calculator", "npk calculator", "urea calculator", "dap calculator", "crop fertilizer"],
    isFeatured: true,
  },
  {
    slug: "npk-calculator",
    title: "NPK Calculator",
    description: "Calculate fertilizer quantities from Nitrogen, Phosphorus, and Potassium requirements. Get Urea, DAP, MOP doses for any area.",
    category: "Agriculture",
    categorySlug: "agriculture",
    icon: "Sprout",
    color: "green",
    keywords: ["npk calculator", "npk fertilizer calculator", "nitrogen phosphorus potassium", "npk per hectare"],
    isNew: true,
  },
  {
    slug: "urea-calculator",
    title: "Urea Calculator",
    description: "Calculate Urea fertilizer dose per hectare, acre, or bigha based on nitrogen requirement. For rice, wheat, maize and 20+ crops.",
    category: "Agriculture",
    categorySlug: "agriculture",
    icon: "Sprout",
    color: "green",
    keywords: ["urea calculator", "urea per hectare", "urea per acre", "urea dose for rice", "urea dose for wheat"],
    isNew: true,
  },
  {
    slug: "dap-calculator",
    title: "DAP Calculator",
    description: "Calculate DAP (Di-ammonium Phosphate 18-46-0) dose per hectare, acre, or bigha. Includes N contribution from DAP.",
    category: "Agriculture",
    categorySlug: "agriculture",
    icon: "Sprout",
    color: "green",
    keywords: ["dap calculator", "dap per hectare", "dap per acre", "di-ammonium phosphate calculator"],
    isNew: true,
  },
  {
    slug: "crop-fertilizer-calculator",
    title: "Crop Fertilizer Calculator",
    description: "ICAR-recommended NPK doses for 25+ crops with split application schedule and cost estimate. Rice, wheat, maize, sugarcane, potato and more.",
    category: "Agriculture",
    categorySlug: "agriculture",
    icon: "Sprout",
    color: "green",
    keywords: ["crop fertilizer calculator", "rice fertilizer calculator", "wheat fertilizer calculator", "icar fertilizer recommendation"],
    isNew: true,
  },
  {
    slug: "fertilizer-per-acre-calculator",
    title: "Fertilizer per Acre Calculator",
    description: "Calculate Urea, DAP, MOP quantities per acre with bag count and cost. Enter N, P, K requirement and acres.",
    category: "Agriculture",
    categorySlug: "agriculture",
    icon: "Sprout",
    color: "green",
    keywords: ["fertilizer per acre", "urea per acre", "dap per acre", "fertilizer bags per acre"],
    isNew: true,
  },
  {
    slug: "fertilizer-per-hectare-calculator",
    title: "Fertilizer per Hectare Calculator",
    description: "Calculate total fertilizer (Urea, DAP, MOP, SSP) for any number of hectares based on crop NPK requirements.",
    category: "Agriculture",
    categorySlug: "agriculture",
    icon: "Sprout",
    color: "green",
    keywords: ["fertilizer per hectare", "urea per hectare", "dap per hectare", "fertilizer dose per hectare"],
    isNew: true,
  },
  {
    slug: "fertilizer-blend-calculator",
    title: "Fertilizer Blend Calculator",
    description: "Mix any combination of fertilizers and see total N, P, K supplied, cost per hectare, and nutrient balance instantly.",
    category: "Agriculture",
    categorySlug: "agriculture",
    icon: "FlaskConical",
    color: "green",
    keywords: ["fertilizer blend calculator", "fertilizer mix calculator", "custom fertilizer blend", "npk blend"],
    isNew: true,
  },
  {
    slug: "fertilizer-cost-calculator",
    title: "Fertilizer Cost Calculator",
    description: "Compare cost of DAP, SSP, NPK complex and other fertilizer routes side by side. Enter local prices to find the cheapest combination.",
    category: "Agriculture",
    categorySlug: "agriculture",
    icon: "Sprout",
    color: "green",
    keywords: ["fertilizer cost calculator", "fertilizer price calculator", "cheapest fertilizer", "fertilizer cost per acre"],
    isNew: true,
  },
  {
    slug: "lawn-fertilizer-calculator",
    title: "Lawn Fertilizer Calculator",
    description: "Calculate how much granular fertilizer your lawn needs in lbs, bags, and cost. Covers 30-0-10, 16-4-8, Milorganite, Urea and more. US sq ft and acre units.",
    category: "Agriculture",
    categorySlug: "agriculture",
    icon: "Sprout",
    color: "green",
    keywords: ["lawn fertilizer calculator", "how much fertilizer for lawn", "fertilizer per square foot", "lawn fertilizer amount"],
    isNew: true,
  },
  {
    slug: "liquid-fertilizer-calculator",
    title: "Liquid Fertilizer Calculator",
    description: "Calculate liquid fertilizer oz per gallon, tank mixing ratios, and hose-end sprayer settings. Covers 20-20-20, Miracle-Gro, fish emulsion, kelp and more.",
    category: "Agriculture",
    categorySlug: "agriculture",
    icon: "FlaskConical",
    color: "green",
    keywords: ["liquid fertilizer calculator", "liquid fertilizer dilution calculator", "hose end sprayer fertilizer calculator", "tank mix fertilizer"],
    isNew: true,
  },
  {
    slug: "dry-fertilizer-calculator",
    title: "Dry Fertilizer Calculator",
    description: "Calculate granular fertilizer quantity in lbs and kg, bags needed, and total cost. Supports 10-10-10, Urea, DAP, MOP, SSP and more. US and metric units.",
    category: "Agriculture",
    categorySlug: "agriculture",
    icon: "Sprout",
    color: "green",
    keywords: ["dry fertilizer calculator", "granular fertilizer calculator", "fertilizer per square foot", "how much fertilizer per 1000 sq ft"],
    isNew: true,
  },
  {
    slug: "cattle-record-keeping",
    title: "Cattle Record Keeping",
    description: "Track herd size, milk production, beef sales, feed and labor costs. Get monthly and annual profit for dairy, beef, or mixed cattle farms.",
    category: "Agriculture",
    categorySlug: "agriculture",
    icon: "Sprout",
    color: "green",
    keywords: ["cattle record keeping", "cattle record keeping app", "dairy farm profit calculator", "beef cattle record keeping", "cow farm income"],
    isNew: true,
  },
  {
    slug: "goat-farm-profit-calculator",
    title: "Goat Farm Profit Calculator",
    description: "Calculate annual revenue, costs, net profit, and payback period for a goat farm. Supports meat, dairy, or mixed goat farming.",
    category: "Agriculture",
    categorySlug: "agriculture",
    icon: "Sprout",
    color: "green",
    keywords: ["goat farm profit calculator", "goat farming profit", "how to start a goat farm", "goat farm income", "goat farming cost"],
    isNew: true,
  },
  {
    slug: "pig-farm-profit-calculator",
    title: "Pig Farm Profit Calculator",
    description: "Calculate annual pig farm profit from sows, litter size, FCR, market weight, and selling price. Get profit per pig and payback period.",
    category: "Agriculture",
    categorySlug: "agriculture",
    icon: "Sprout",
    color: "green",
    keywords: ["pig farm profit calculator", "pig farming profit", "how to start a pig farm", "pig farm income calculator", "swine farm calculator"],
    isNew: true,
  },
  {
    slug: "perimenopause-age-calculator",
    title: "Perimenopause Age Calculator",
    description: "Find out what perimenopause stage you are in. Enter age, menstrual status, and symptoms to estimate your stage and years to menopause.",
    category: "Health",
    categorySlug: "health",
    icon: "Heart",
    color: "pink",
    keywords: ["perimenopause age calculator", "am i in perimenopause", "perimenopause stage calculator", "when will i reach menopause"],
    isNew: true,
    isFeatured: true,
  },
  {
    slug: "inflation-calculator-india",
    title: "Inflation Calculator India",
    description: "Calculate the inflation-adjusted value of the Indian Rupee (₹). Check purchasing power from 1980–2025 with India CPI context and RBI target rates.",
    category: "Finance",
    categorySlug: "finance",
    icon: "TrendingUp",
    color: "blue",
    keywords: ["inflation calculator india", "rupee inflation calculator", "property inflation calculator india", "reverse inflation calculator india"],
    isNew: true,
  },
  {
    slug: "salary-inflation-calculator",
    title: "Salary Inflation Calculator",
    description: "Check if your salary is keeping up with inflation. Compare nominal vs real purchasing power with year-by-year breakdown.",
    category: "Finance",
    categorySlug: "finance",
    icon: "TrendingUp",
    color: "blue",
    keywords: ["salary inflation calculator", "wage inflation calculator", "real salary calculator", "inflation adjusted salary"],
    isNew: true,
  },
  {
    slug: "future-value-inflation-calculator",
    title: "Future Value Inflation Calculator",
    description: "Calculate how much money you'll need in the future to match today's purchasing power. Supports any currency and custom inflation rate.",
    category: "Finance",
    categorySlug: "finance",
    icon: "TrendingUp",
    color: "blue",
    keywords: ["future inflation calculator", "future value calculator inflation", "calculate inflation adjusted value", "inflation adjusted future value"],
    isNew: true,
  },
  {
    slug: "past-inflation-calculator",
    title: "Past Inflation Calculator",
    description: "Find out what money was worth in any past year. Calculate historical purchasing power using US CPI data from 1980 to 2025.",
    category: "Finance",
    categorySlug: "finance",
    icon: "TrendingUp",
    color: "blue",
    keywords: ["past inflation calculator", "inflation calculator by year", "historical inflation calculator", "what was money worth", "reverse inflation calculator"],
    isNew: true,
  },
  {
    slug: "sip-calculator",
    title: "SIP Calculator",
    description: "Calculate SIP returns, maturity value, and wealth gain. Supports monthly SIP and lump sum investments with expected return rate.",
    category: "Finance",
    categorySlug: "finance",
    icon: "TrendingUp",
    color: "blue",
    keywords: ["sip calculator", "sip return calculator", "mutual fund sip", "systematic investment plan"],
    isNew: true,
  },
  {
    slug: "emi-calculator",
    title: "EMI Calculator",
    description: "Calculate monthly EMI for home loan, car loan, personal loan and education loan. Get total interest and payment breakdown.",
    category: "Finance",
    categorySlug: "finance",
    icon: "TrendingUp",
    color: "blue",
    keywords: ["emi calculator", "home loan emi", "car loan emi", "loan calculator india"],
    isNew: true,
  },
  {
    slug: "paint-calculator",
    title: "Paint Calculator",
    description: "Calculate how many litres of paint you need for walls, ceiling, or full room. Deducts doors and windows. Supports multiple coats.",
    category: "Construction",
    categorySlug: "construction",
    icon: "Grid3x3",
    color: "orange",
    keywords: ["paint calculator", "how much paint do i need", "wall paint calculator", "paint litre calculator"],
    isNew: true,
  },
  {
    slug: "renovation-cost-calculator",
    title: "Renovation Cost Calculator",
    description: "Estimate kitchen, bathroom, whole house, basement, or room renovation cost by square footage, finish quality, and region, with a materials vs labor breakdown.",
    category: "Construction",
    categorySlug: "construction",
    icon: "Home",
    color: "orange",
    keywords: ["renovation cost calculator", "home renovation cost calculator", "kitchen renovation cost calculator", "bathroom renovation cost calculator", "whole house renovation cost calculator"],
    isNew: true,
    isFeatured: true,
  },
  {
    slug: "tile-calculator",
    title: "Tile Calculator",
    description: "Calculate tiles, grout, and materials needed for floor, wall, shower, ceiling, or backsplash tiling projects.",
    category: "Construction",
    categorySlug: "construction",
    icon: "Grid3x3",
    color: "orange",
    keywords: ["tile calculator", "floor tile calculator", "shower tile calculator", "backsplash calculator"],
    isFeatured: true,
  },
  {
    slug: "brick-calculator",
    title: "Brick Calculator",
    description: "Calculate number of bricks, cement bags, and sand needed for any wall. Supports standard Indian, modular, and custom brick sizes.",
    category: "Construction",
    categorySlug: "construction",
    icon: "Grid3x3",
    color: "orange",
    keywords: ["brick calculator", "how many bricks do i need", "brick wall calculator", "bricks per square foot"],
    isNew: true,
  },
  {
    slug: "brick-calculator-square-feet",
    title: "Brick Calculator – Square Feet",
    description: "Calculate bricks per square foot for any wall thickness. Get total bricks, cement, sand and cost. Standard Indian and custom brick sizes.",
    category: "Construction",
    categorySlug: "construction",
    icon: "Grid3x3",
    color: "orange",
    keywords: ["brick calculator square feet", "bricks per square foot", "bricks calculation formula in feet"],
    isNew: true,
  },
  {
    slug: "boundary-wall-brick-calculator",
    title: "Boundary Wall Brick Calculator",
    description: "Calculate bricks, cement and sand for compound/boundary wall construction in India. 4.5 and 9-inch wall options.",
    category: "Construction",
    categorySlug: "construction",
    icon: "Grid3x3",
    color: "orange",
    keywords: ["boundary wall brick calculator", "brick calculator india", "compound wall brick calculator"],
    isNew: true,
  },
  {
    slug: "paver-brick-calculator",
    title: "Paver Brick Calculator",
    description: "Calculate pavers needed for patio, driveway, walkway or garden path. Enter area and paver size for count, sand and cost.",
    category: "Construction",
    categorySlug: "construction",
    icon: "Grid3x3",
    color: "orange",
    keywords: ["paver brick calculator", "patio brick calculator", "driveway paver calculator"],
    isNew: true,
  },
  {
    slug: "drip-irrigation-calculator",
    title: "Drip Irrigation Calculator",
    description: "Calculate daily water requirement, number of drippers, total flow rate, and irrigation duration for any crop. Supports acres, hectares, bigha. 18 India-specific crops.",
    category: "Agriculture",
    categorySlug: "agriculture",
    icon: "Sprout",
    color: "green",
    keywords: ["drip irrigation calculator", "drip irrigation calculator india", "drip irrigation flow rate calculator", "irrigation water requirement calculator"],
    isNew: true,
    isFeatured: true,
  },
  {
    slug: "electrical-load-calculator",
    title: "Electrical Load Calculator",
    description: "Calculate total home or office electrical load in kW and kVA. Get circuit breaker size, monthly units, and electricity bill estimate. Single and three-phase support.",
    category: "Electrical",
    categorySlug: "electrical",
    icon: "Zap",
    color: "yellow",
    keywords: ["electrical load calculator", "electrical load calculator india", "residential electrical load calculator", "circuit breaker size calculator", "electricity bill calculator"],
    isNew: true,
    isFeatured: true,
  },
  {
    slug: "concrete-calculator",
    title: "Concrete Calculator",
    description: "Calculate how many bags of concrete you need for driveways, patios, and slabs. Enter dimensions, depth, and bag size to get instant results with cost estimates.",
    category: "Construction & Home",
    categorySlug: "construction",
    icon: "Grid3x3",
    color: "orange",
    keywords: ["concrete calculator", "how many bags of concrete do i need", "concrete bags calculator", "driveway concrete calculator", "patio concrete calculator"],
    isNew: true,
    isFeatured: true,
  },
  {
    slug: "mulch-calculator",
    title: "Mulch Calculator",
    description: "Calculate cubic yards and bags of mulch needed for landscaping. Supports bark, wood chips, compost, pine straw, and rubber mulch with cost estimates.",
    category: "DIY & Landscaping",
    categorySlug: "diy-landscaping",
    icon: "Sprout",
    color: "green",
    keywords: ["mulch calculator", "how much mulch do i need", "mulch calculator cubic yards", "landscape mulch calculator", "wood chips calculator"],
    isNew: true,
    isFeatured: true,
  },
  {
    slug: "tdee-calculator",
    title: "TDEE Calculator",
    description: "Calculate your Total Daily Energy Expenditure (TDEE) and get personalized calorie and macro targets for fat loss, muscle gain, or maintenance.",
    category: "Health",
    categorySlug: "health",
    icon: "Heart",
    color: "pink",
    keywords: ["tdee calculator", "calorie calculator", "macro calculator", "daily calorie needs"],
    isNew: true,
    isFeatured: true,
  },
  {
    slug: "real-estate-commission-calculator",
    title: "Real Estate Commission Calculator",
    description: "Calculate listing and buyer's agent commission, net proceeds to seller, and agent take-home after brokerage split. Includes a general sales commission calculator.",
    category: "Finance",
    categorySlug: "finance",
    icon: "DollarSign",
    color: "blue",
    keywords: ["real estate commission calculator", "realtor commission calculator", "real estate agent commission calculator", "commission calculator", "sales commission calculator"],
    isNew: true,
    isFeatured: true,
  },
  {
    slug: "mortgage-calculator",
    title: "Mortgage Calculator",
    description: "Calculate monthly mortgage payments including principal, interest, property tax, insurance, PMI, and HOA fees with full amortization breakdown.",
    category: "Finance",
    categorySlug: "finance",
    icon: "DollarSign",
    color: "blue",
    keywords: ["mortgage calculator", "home loan calculator", "monthly payment calculator"],
    isNew: true,
    isFeatured: true,
  },
  {
    slug: "ac-unit-calculator",
    title: "AC Unit Size Calculator",
    description: "Calculate the correct air conditioner tonnage and BTU needed for your space based on square footage, climate, and insulation.",
    category: "Home & HVAC",
    categorySlug: "home-hvac",
    icon: "Zap",
    color: "blue",
    keywords: ["ac calculator", "air conditioner size", "hvac calculator", "ac unit size"],
    isNew: true,
    isFeatured: true,
  },
  {
    slug: "drywall-calculator",
    title: "Drywall Calculator",
    description: "Calculate drywall sheets, joint compound, and tape needed for your project with waste allowance and cost estimates.",
    category: "Construction & Home",
    categorySlug: "construction",
    icon: "Grid3x3",
    color: "orange",
    keywords: ["drywall calculator", "how many sheets of drywall", "drywall cost calculator"],
    isNew: true,
    isFeatured: true,
  },
  {
    slug: "insulation-calculator",
    title: "Insulation Calculator",
    description: "Calculate how many batts, rolls, or bags of insulation you need. Fiberglass, cellulose, spray foam, and mineral wool support with R-value recommendations.",
    category: "Home & HVAC",
    categorySlug: "home-hvac",
    icon: "Zap",
    color: "blue",
    keywords: ["insulation calculator", "blown in insulation calculator", "spray foam insulation calculator", "fiberglass insulation calculator", "attic insulation calculator"],
    isNew: true,
    isFeatured: true,
  },
  {
    slug: "roofing-calculator",
    title: "Roofing Calculator",
    description: "Calculate roofing squares, material quantity, and project cost. Accounts for roof pitch, material type, and waste allowance. Supports asphalt, metal, tile, and composite.",
    category: "Construction & Home",
    categorySlug: "construction",
    icon: "Home",
    color: "orange",
    keywords: ["roofing calculator", "roofing calculator square feet", "roof calculator", "asphalt shingles calculator", "roofing squares calculator"],
    isNew: true,
    isFeatured: true,
  },
  {
    slug: "flooring-calculator",
    title: "Flooring Calculator",
    description: "Calculate how many boxes of flooring materials you need for any room. Supports laminate, vinyl plank, hardwood, tile, and carpet with cost estimates.",
    category: "Construction & Home",
    categorySlug: "construction",
    icon: "Home",
    color: "orange",
    keywords: ["flooring calculator", "flooring calculator square feet", "laminate flooring calculator", "vinyl flooring calculator", "how many boxes of flooring"],
    isNew: true,
    isFeatured: true,
  },
  {
    slug: "wood-calculator",
    title: "Wood Calculator",
    description: "Calculate wood volume in cubic feet, board feet, and cords. Estimate weight for lumber, hardwood, plywood, and firewood. Perfect for woodworking and firewood ordering.",
    category: "DIY & Landscaping",
    categorySlug: "diy-landscaping",
    icon: "TreePine",
    color: "green",
    keywords: ["wood calculator", "cord of wood calculator", "board feet calculator", "cubic feet wood calculator", "firewood calculator"],
    isNew: true,
    isFeatured: true,
  },
  {
    slug: "lumber-calculator",
    title: "Lumber Calculator",
    description: "Calculate board feet and lumber needed for decks, framing, joists, and fencing. Supports various lumber sizes, spacing options, and cost estimation.",
    category: "Construction & Home",
    categorySlug: "construction",
    icon: "Home",
    color: "orange",
    keywords: ["lumber calculator", "board feet calculator", "deck lumber calculator", "framing lumber calculator", "lumber cost calculator"],
    isNew: true,
    isFeatured: true,
  },
  {
    slug: "furnace-btu-calculator",
    title: "Furnace BTU Calculator",
    description: "Calculate the furnace size and BTU heating capacity needed for your home. Based on square footage, climate zone, and insulation level.",
    category: "HVAC & Climate",
    categorySlug: "home-hvac",
    icon: "Flame",
    color: "blue",
    keywords: ["furnace btu calculator", "furnace size calculator", "heating btu calculator", "what size furnace do I need", "furnace calculator"],
    isNew: true,
    isFeatured: true,
  },
  {
    slug: "ductwork-calculator",
    title: "Ductwork Calculator",
    description: "Calculate HVAC duct size, diameter, and airflow (CFM) for round and rectangular ducts. Get friction loss estimates and proper duct sizing.",
    category: "HVAC & Climate",
    categorySlug: "home-hvac",
    icon: "Wind",
    color: "blue",
    keywords: ["ductwork calculator", "duct size calculator", "cfm calculator", "hvac ductwork calculator", "duct diameter calculator", "ductwork sizing"],
    isNew: true,
    isFeatured: true,
  },
  {
    slug: "tariff-calculator",
    title: "Tariff Calculator",
    description: "Estimate US and EU customs duty, import VAT, and total landed cost by product category and country of origin. Includes de minimis thresholds.",
    category: "Trade & Import",
    categorySlug: "trade",
    icon: "Ship",
    color: "blue",
    keywords: ["tariff calculator", "import duty calculator", "import duty calculator usa", "eu import duty calculator", "customs duty calculator", "landed cost calculator"],
    isNew: true,
    isFeatured: true,
  },
  {
    slug: "wire-gauge-calculator",
    title: "Wire Gauge Calculator",
    description: "Calculate the correct AWG wire gauge for electrical circuits. Based on current (amps), voltage, and distance. Supports 12V, 24V, 120V, 240V systems.",
    category: "Electrical",
    categorySlug: "electrical",
    icon: "Zap",
    color: "yellow",
    keywords: ["wire gauge calculator", "awg calculator", "wire size calculator", "12v wire gauge calculator", "electrical wire gauge calculator", "speaker wire gauge calculator"],
    isNew: true,
    isFeatured: true,
  },
];

export const categories: Category[] = [
  {
    slug: "finance",
    title: "Finance",
    description: "Calculators for investments, loans, inflation, mortgages, retirement, and personal finance.",
    icon: "DollarSign",
    color: "blue",
    tools: tools.filter((t) => t.categorySlug === "finance"),
  },
  {
    slug: "agriculture",
    title: "Agriculture",
    description: "Farm and garden calculators for fertilizer, crop yield, irrigation, livestock, and more.",
    icon: "Sprout",
    color: "green",
    tools: tools.filter((t) => t.categorySlug === "agriculture"),
  },
  {
    slug: "construction",
    title: "Construction & Home",
    description: "Building calculators for tiles, paint, concrete, drywall, roofing, flooring, lumber, and materials.",
    icon: "HardHat",
    color: "orange",
    tools: tools.filter((t) => t.categorySlug === "construction"),
  },
  {
    slug: "health",
    title: "Health & Fitness",
    description: "Health and fitness calculators for wellness, fitness, nutrition, and personal health tracking.",
    icon: "Heart",
    color: "pink",
    tools: tools.filter((t) => t.categorySlug === "health"),
  },
  {
    slug: "electrical",
    title: "Electrical",
    description: "Electrical calculators for load, circuit breakers, energy consumption, and electricity bill estimation.",
    icon: "Zap",
    color: "yellow",
    tools: tools.filter((t) => t.categorySlug === "electrical"),
  },
  {
    slug: "diy-landscaping",
    title: "DIY & Landscaping",
    description: "Landscaping and outdoor project calculators for mulch, wood, yard design, and more.",
    icon: "Sprout",
    color: "green",
    tools: tools.filter((t) => t.categorySlug === "diy-landscaping"),
  },
  {
    slug: "home-hvac",
    title: "HVAC & Climate",
    description: "HVAC and home climate calculators for sizing AC units, furnaces, and insulation.",
    icon: "Wind",
    color: "blue",
    tools: tools.filter((t) => t.categorySlug === "home-hvac"),
  },
  {
    slug: "trade",
    title: "Trade & Import",
    description: "Calculators for import duty, tariffs, VAT, and landed cost for shipping into the US or EU.",
    icon: "Ship",
    color: "blue",
    tools: tools.filter((t) => t.categorySlug === "trade"),
  },
];

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((t) => t.slug === slug);
}

export function getRelatedTools(slug: string, limit = 4): Tool[] {
  const tool = getToolBySlug(slug);
  if (!tool) return tools.slice(0, limit);
  return tools
    .filter((t) => t.slug !== slug && t.categorySlug === tool.categorySlug)
    .slice(0, limit)
    .concat(tools.filter((t) => t.categorySlug !== tool.categorySlug).slice(0, limit - 1))
    .slice(0, limit);
}
